[package]
name = "cripto"
version = "0.1.0"
edition = "2021"

[dependencies]
sha256 = "1.5.0"
rand = "0.8.5"
rsa = { version="0.9.6", features=["sha2"] }
serde = { version="1.0.210", features=["derive"] }
serde_json = { version="1.0.128" }
